// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentRunKind } from "./AgentRunKind";
import type { WritePolicy } from "./WritePolicy";

export type AgentRunRequest = { kind: AgentRunKind, vaddr: string, write_policy: WritePolicy | null, };
