// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AgentRunResponse = { agent: string, kind: string, job_id: string, text: string, created_finding_id: string | null, applied: boolean, };
