// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Target } from "./Target";
import type { WritePolicy } from "./WritePolicy";

export type ContextPack = { workspace_summary: string, target: Target, annotations: Record<string, unknown>, prior_findings: Array<string>, allowed_tools: Array<string>, write_policy: WritePolicy, output_schema: Record<string, unknown>, };
