// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CreatedBy = { "kind": "tool", name: string, } | { "kind": "agent", agent: string, } | { "kind": "user" };
