// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatedBy } from "./CreatedBy";
import type { Evidence } from "./Evidence";
import type { FindingKind } from "./FindingKind";
import type { Severity } from "./Severity";

/**
 * Input for creating a finding via API/MCP.
 */
export type CreateFinding = { kind: FindingKind, severity: Severity, vaddr: string | null, rule: string, rationale: string, evidence: Array<Evidence>, suggested_actions: Array<string>, created_by: CreatedBy, };
