// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Source } from "./Source";

/**
 * Granular event delta.  Wire JSON uses dotted `type` discriminator
 * (`function.renamed`, `comment.added`, …) so it reads naturally on the
 * browser side.
 */
export type Event = { "type": "function.renamed", vaddr: string, old: string | null, new: string, source: Source, ts: bigint, } | { "type": "comment.added", vaddr: string, text: string, source: Source, ts: bigint, } | { "type": "note.added", id: bigint, vaddr: string | null, text: string, source: Source, ts: bigint, } | { "type": "note.deleted", id: bigint, source: Source, ts: bigint, } | { "type": "vuln_score.set", vaddr: string, score: number, source: Source, ts: bigint, } | { "type": "finding.created", id: string, kind: string, severity: string, vaddr: string | null, rule: string, source: Source, ts: bigint, } | { "type": "finding.updated", id: string, status: string | null, owner: string | null, source: Source, ts: bigint, } | { "type": "job.started", id: string, kind: string, ts: bigint, } | { "type": "job.progress", id: string, pct: number, } | { "type": "job.finished", id: string, status: string, ts: bigint, } | { "type": "job.cancelled", id: string, ts: bigint, } | { "type": "job.failed", id: string, error: string, ts: bigint, } | { "type": "tool.call", id: string, job_id: string | null, name: string, source: Source, ts: bigint, } | { "type": "tool.result", id: string, name: string, ok: boolean, bytes: number, ts: bigint, } | { "type": "navigation", vaddr: string, source: Source, ts: bigint, };
