// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Evidence = { "kind": "disasm", vaddr: string, length: number, } | { "kind": "decompile", vaddr: string, } | { "kind": "xref", from: string, to: string, } | { "kind": "string", offset: bigint, text: string, } | { "kind": "import", name: string, } | { "kind": "tool_output", tool: string, args: Record<string, unknown>, snippet: string, };
