// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CreatedBy } from "./CreatedBy";
import type { Evidence } from "./Evidence";
import type { FindingKind } from "./FindingKind";
import type { FindingStatus } from "./FindingStatus";
import type { Severity } from "./Severity";

export type Finding = { id: string, kind: FindingKind, severity: Severity, vaddr: string | null, rule: string, rationale: string, evidence: Array<Evidence>, suggested_actions: Array<string>, status: FindingStatus, owner: string | null, created_by: CreatedBy, notes: Array<bigint>, created_at: bigint, updated_at: bigint, };
