// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FindingKind = "vuln" | "hash_match" | "import_of_interest" | "cfg_anomaly" | "string_of_interest" | "custom";
