// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JobKind } from "./JobKind";
import type { JobStatus } from "./JobStatus";

export type Job = { id: string, kind: JobKind, status: JobStatus, created_at: bigint, finished_at: bigint | null, error: string | null, result_summary: string | null, progress: number, };
