// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type JobKind = "scan_vuln" | "match_all_functions" | "decompile" | "agent_bridge" | "custom";
