// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PaletteResult = { "kind": "navigate", vaddr: string, } | { "kind": "text", text: string, } | { "kind": "ok", message: string, } | { "kind": "error", message: string, };
