// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaybookFinding } from "./PlaybookFinding";
import type { PlaybookId } from "./PlaybookId";
import type { PlaybookStep } from "./PlaybookStep";

export type PlaybookRun = { id: PlaybookId, title: string, summary: string, steps: Array<PlaybookStep>, proposed_findings: Array<PlaybookFinding>, };
