// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlaybookRunRequest = { max_functions: number | null, create_findings: boolean, };
