// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaybookEvidence } from "./PlaybookEvidence";

export type PlaybookStep = { title: string, status: string, evidence: Array<PlaybookEvidence>, };
