// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PlaybookId } from "./PlaybookId";

export type Playbook = { id: PlaybookId, title: string, audience: string, goal: string, steps: Array<string>, };
