// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Evidence } from "./Evidence";
import type { FindingKind } from "./FindingKind";
import type { Severity } from "./Severity";

export type PlaybookFinding = { kind: FindingKind, severity: Severity, vaddr: string | null, rule: string, rationale: string, evidence: Array<Evidence>, suggested_actions: Array<string>, };
