// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlaybookId = "malware_triage" | "ctf_flag_hunt" | "vulnerability_audit" | "capability_survey" | "command_handler_hunt" | "license_check_hunt" | "crypto_secret_hunt" | "network_parser_hunt" | "auth_bypass_review";
