// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CommentEntry } from "./CommentEntry";
import type { NoteEntry } from "./NoteEntry";
import type { RenameEntry } from "./RenameEntry";
import type { VulnScoreEntry } from "./VulnScoreEntry";

export type ProjectSnapshot = { renames: Array<RenameEntry>, comments: Array<CommentEntry>, notes: Array<NoteEntry>, vuln_scores: Array<VulnScoreEntry>, };
