// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { WorkspaceInfo } from "./WorkspaceInfo";

/**
 * Snapshot for `GET /api/workspaces`.
 */
export type RegistrySnapshot = { active: string | null, workspaces: Array<WorkspaceInfo>, };
