// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who originated a mutation or call.  Every event carries this so the UI can
 * attribute ("Claude renamed this 3s ago" vs "you renamed this 2 days ago").
 */
export type Source = "user" | "claude" | "codex" | "plugin" | "tool" | "system";
