// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Target = { "kind": "function", vaddr: string, } | { "kind": "range", start: string, end: string, } | { "kind": "finding", id: string, };
