// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FindingStatus } from "./FindingStatus";

export type UpdateFinding = { status: FindingStatus | null, owner: string | null, append_notes: Array<bigint>, };
