// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * JSON snapshot of workspace metadata returned by `GET /api/workspace`.
 */
export type WorkspaceInfo = { binary_path: string, display_name: string, workspace_hash: string, allow_patch: boolean, allow_exec: boolean, };
